### ISSUE TITLE
Community set does not care about platform in evolution measurement

### ISSUE THREAD

**Issue by hrukalive** [pnnl/socialsim_package#18]
```python3
else:
    community_directory = metadata.community_directory
    communities = metadata.communities
    self.community_set = add_communities_to_dataset(dataset, # <- should here be self.data?
                                                            community_directory,
                                                            communities)

if metadata is None or metadata.node_list is None:
```

**Comment by Maria-G** [comment]
'communities' in this case are groups of informationIDs specified through community_directory in the metadata. These communities can be applied regardless of platform specified and platform is specified at instantiation for evolution. 

I have updated the add_communities_to_dataset() function to rely on the self.data property rather than the dataset object passed to be more robust to varied platform specification.
