### ISSUE TITLE
Libraries burst_detection, tsfresh missing from requirements

### ISSUE THREAD

**Issue by mbamba** [pnnl/socialsim_package#2]
Did install package using: 

> python setup.py install --force

Running task_runner.py produced:

>  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/run.py", line 12, in <module>
    from .measurements import SocialActivityMeasurements
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/__init__.py", line 6, in <module>
    from .recurrence          import RecurrenceMeasurements
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/recurrence.py", line 6, in <module>
    import burst_detection as bd
ModuleNotFoundError: No module named 'burst_detection'

>   File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/__init__.py", line 6, in <module>
    from .recurrence          import RecurrenceMeasurements
  File "anaconda2/envs/socialsim_cp2/lib/python3.6/site-packages/socialsim/measurements/recurrence.py", line 9, in <module>
    from tsfresh import extract_features
ModuleNotFoundError: No module named 'tsfresh'

Solved it by running:

> pip install burst_detection
> pip install tsfresh

**Comment by emily-grace** [comment]
We've added the new packages (burst_detection and tsfresh) to the setup.py requirements.

We've also modified the install process so the dependencies are handled by the setup file rather than a requirements file, because the requirements file was not compatible across multiple operating systems.

The current README includes the most up to date install instructions.
