### ISSUE TITLE
Questions about running metrics (also posted to Wiki)

### ISSUE THREAD

**Issue by alw4ey** [pnnl/socialsim_package#38]
We are using the extract_ground_truth to pull the ground truth and metadata data frame for metrics testing from the raw data, but for Twitter I am running into a memory error if I try to run the whole set at once (tongue).  I can throw more memory at it (and have), and that may work okay, but I was wondering if there is any issue with extracting ground truth from the six files as separate parallel processes.  My concern is that if the parent and child tweets live in separate files, we may not get the rootId for the child tweet.  Is that a possibility?

Also, is it possible to pass a date range to the extract_ground_truth function?  I have not seen examples of that sort, but I may have overlooked it.

Thanks!

**Comment by Maria-G** [comment]
We ran the extraction script on smaller chunks of the data rather than running on the full set.  This may cause issues with determining the rootID of the posts, but we are not using the rootID for any of the evaluation in this CP. The parentID, which is used for the network construction, is determined directly from an individual data record, so the parentID is not impacted by running extraction on data subsets.

The extract_ground_truth script does not currently have an option to filter by date, so the files would need to be split by data before passing them to the extraction script or you would need to subset by date after extraction.
